# docker stack deploy -c stack.yml nlp
version: '3.9'

services:
  nlp-client:
    image: garystafford/nlp-client:1.2.1
    networks:
      - nlp-demo
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - NLP_CLIENT_PORT
      - RAKE_ENDPOINT
      - PROSE_ENDPOINT
      - LANG_ENDPOINT
      - DYNAMO_ENDPOINT
      - API_KEY
  rake-app:
    image: garystafford/rake-app:1.2.1
    networks:
      - nlp-demo
    environment:
      - RAKE_PORT
      - API_KEY
  prose-app:
    image: garystafford/prose-app:1.2.1
    networks:
      - nlp-demo
    environment:
      - PROSE_PORT
      - API_KEY
  lang-app:
    image: garystafford/lang-app:1.2.1
    networks:
      - nlp-demo
    environment:
      - LANG_PORT
      - API_KEY
  dynamo-app:
    image: garystafford/dynamo-app:1.2.1
    networks:
      - nlp-demo
    environment:
      - DYNAMO_PORT
      - API_KEY

networks:
  nlp-demo:

volumes:
  data: { }
