# docker stack deploy -c stack.yml nlp
version: '3.9'

services:
  nlp-client:
    image: garystafford/nlp-client:1.1.0
    networks:
      - nlp-demo
    ports:
      - 8080:8080
    environment:
      - NLP_CLIENT_PORT
      - RAKE_ENDPOINT
      - PROSE_ENDPOINT
      - LANG_ENDPOINT
      - DYNAMO_ENDPOINT
      - AUTH_KEY
  rake-app:
    image: garystafford/rake-app:1.1.0
    networks:
      - nlp-demo
    environment:
      - RAKE_PORT
      - AUTH_KEY
  prose-app:
    image: garystafford/prose-app:1.1.0
    networks:
      - nlp-demo
    environment:
      - PROSE_PORT
      - AUTH_KEY
  lang-app:
    image: garystafford/lang-app:1.1.0
    networks:
      - nlp-demo
    environment:
      - LANG_PORT
      - AUTH_KEY
  dynamo-app:
    image: garystafford/dynamo-app:1.1.0
    networks:
      - nlp-demo
    environment:
      - DYNAMO_PORT
      - AUTH_KEY

networks:
  nlp-demo:

volumes:
  data: {}
