apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nlp-app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . }}
        {{- end }}