version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - sh buildspec_files/build.sh

artifacts:
  files:
    - '**/*'
  base-directory: '/'
  discard-paths: yes